version: '2'
services:
  postgres:
    image: postgres
    environment:

      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'starwars_quotes'
    networks:
      - app_net
  app_server:
    build: .
    environment:
      APP_ENV: development
    command: ruby app.rb
    ports:
      - "8000:4567"
    networks:
      - app_net
    depends_on:
      - postgres

networks:
  app_net:
    driver: bridge
