version: '2'
services:
  postgres:
    image: postgres
    networks:
      - app_net
  app_server:
    build: .
    environment:
      APP_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command: ruby app.rb
    ports:
      - "8000:4567"
    networks:
      - app_net
    depends_on:
      - postgres

networks:
  app_net:
    driver: bridge
